### PR TITLE
Add `exp` as a MathFunction (like log, ln, sin, cos, etc.)

### PR DESCRIPTION
**Pull request by drgrice1**
Note that `exp` will need to be added to the autoCommands configuration option in PG's mqeditor.js for this to work for WeBWorK.

This was requested in issue #17.

This builds on #20 (and so the build in `dist` contains everything).

### CODE REVIEW

**Comment by drgrice1** [comment]
Another possible direction to go with this is to make typing `exp` turn into `e` with an exponent.  I am not sure how hard that would be to implement though.  What do you thing @dlglin?

**Comment by Alex-Jordan** [comment]
I'd rather leave `exp` as `exp`. When the argument is a complicated expression, it's ugly to put it up in the exponent.

**Comment by drgrice1** [comment]
I will leave it as is then.

**Review by Alex-Jordan — APPROVED** [review]

**Review by pstaabp — APPROVED** [review]

**Comment by Alex-Jordan** [comment]
This now has a conflict with the minimized js file, following the merge of #20. I'd merge this except for that issue.

**Pull request merged**
