### PR TITLE
Don't send a backslash when submitting variables.

### PR DESCRIPTION
**Pull request by somiaj**
This makes it so the check to remove any initial backslash when submitting variables (such as when using autocompleted Greek letters) is processed for all variables, since there isn't a case where the backslash should be sent to pg.

### CODE REVIEW

**Review by drgrice1 — APPROVED** [review]
This looks good.  Thanks for making the suggested change.

**Review by drgrice1 — COMMENTED** [review]
I think there is one other small change needed here.  With the deletion of the usage of `isPartOfOperator` on line 466, this obsoletes that variable.  That was the only thing it was used for.  So the variable should be deleted entirely from the code.  That means delete lines 458 and lines 518 (currently line 516 in this pull request).

**Comment by somiaj** [comment]
Updated. Thanks for pointing that out.

**Comment by drgrice1** [comment]
I am going to go ahead and merge this.

**Pull request merged**
