### PR TITLE
Space before math function

### PR DESCRIPTION
**Pull request by drgrice1**
Inject a space before `MathFunction`s when preceeded by a letter.
    
This fixes https://github.com/openwebwork/webwork2/issues/2209.

### CODE REVIEW

**Comment by drgrice1** [comment]
Note the only change in this pull request is on line 1471 (now line 1488 - 1490) of `src/commands/mathElements.ts`.

**Comment by drgrice1** [comment]
To test this (or #27) with webwork2 and pg copy the `dist/mathquill.js` file to `/opt/webwork/pg/htdocs/node_modules/mathquill/dist`.

**Comment by Alex-Jordan** [comment]
I'm not opposed to this, just taking time to think it over. A thought I have is that while I agree that it would be better if WW/PG did not support `asin` and friends, the fact is that we have it already in too many problems to make it go away. (Is that a fact? I haven't actually checked yet...)

My next thought is that if MathObjects support some piece of math notation, then MathQuill should support it too. Even when it's something like this that we might not love notationally. Somewhere there was a thread I can't find, where I catalogued MathObject operators (including a few that are only in some not-so-uncommon contexts) that MQ could support explicitly.

So a different approach would be for MathQuill to actually support `asin`, `acos`, `atan` and when a student types these, it becomes `arcsin`, `arccos`, and `arctan`.

**Comment by drgrice1** [comment]
I am not for that.

First, I don't think that will be easy to implement.

Second, I don't agree that everything must be supported by MathQuill.  `asin`, `acos`, and `atan` are not mathematical notations.  They are computer programmer shortcuts that should have never existed.  All to save having to type two characters.  These are even listed as abbreviated forms used in computer programming languages on Wikipedia (https://en.wikipedia.org/wiki/Inverse_trigonometric_functions).

What happens then when someone wants `a * sin(x)` (which is what brought this up to begin with)?  They type `asin` and it becomes `arcsin`.  Now they have to delete that and try again.

**Comment by Alex-Jordan** [comment]
Yeah I don't disagree that it would be better to not have `asin`. No need to persuade me on that point. But my point was more that we are stuck with what we are stuck with.

Maybe we deprecate `asin` somehow in MathObjects? Like if it shows up in a formula, there is one of those instructor-only warnings?

> They type asin and it becomes arcsin. Now they have to delete that and try again.

Yeah but that's 99% less of a problem than the original report. In this scenario, the student sees it became arcsin, and it's natural to do it again with a space or an asterisk. In the original report, the student has no idea what the issue actually is.

**Comment by drgrice1** [comment]
You should note that if a problem author uses `asin` for an answer then it is displayed as `sin^{-1}`.  So even the display format by PG does not show `asin`.

Consider the following MWE.
```
DOCUMENT();
loadMacros('PGstandard.pl', 'PGML.pl', 'PGcourse.pl');
Context()->flags->set(reduceConstants => 0, reduceConstantFunctions => 0, formatStudentAnswer => 'parsed');
$asin = Formula('asin(0)');
BEGIN_PGML
Enter [`[$asin]`]: [_]{$asin}
END_PGML
ENDDOCUMENT();
```

In the problem `sin^{-1}` is shown, and the correct answer is `sin^{-1}`.  However, I don't like what PG does with the student "parsed" answer.  If the student enters `arcsin` or `sin^{-1}` it is displayed as `asin` for the "You Entered" answer.  That isn't good.  The "Preview of Your Answer" shows as `sin^{-1}` though.  This is true regardless of if MathQuill is enabled of course.

The same behavior is exhibited for `acos` and `atan`.

**Comment by Alex-Jordan** [comment]
> You should note that if a problem author uses asin for an answer then it is displayed as sin^{-1}.

Yes, I know that. That is kind of my point:

* PG turns `asin` into something more recognizable.
* Let MQ turn `asin` into something more recognizable too.

I'm not concerned if it's `arcsin` or `sin^-1`, although my personal preference is to the former.

You said it would not be easy to implement, and I take your word on that. But if it can turn a typed `sqrt` into `\sqrt{}`, is it that much different to turn `asin` into `\arcsin{}`? Does it actually just prepend a backslash or is it more flexible than that? 

All this aside, what are your thoughts on deprecating `asin` in MathObjects? Then I don't get hung up on the issue that if something is officially supported one place, it should be supported at other places.

**Comment by drgrice1** [comment]
Technically, MathQuill doesn't turn `sqrt` into `\sqrt{}`.  When `sqrt` is typed, a JavaScript object is created, particularly, an instance of the `SquareRoot` class.  If the `latex` method for the MathQuill instance is called then that outputs `\sqrt{...}`.  If the `text` method is called then it outputs `sqrt(...)`.  If the `html` method is called then it outputs what you see on the screen.

For the trig functions, `exp`, `ln`, and `log` an instance of the `MathFunction` class is created.  When the `latex` method is called it outputs `\fnname\left(...\right)`.  When the `text` method is called it outputs `fnname(...)`.  Of course the `html` method is what you see.  Note that `fnname` is really the `ctrlSeq` for the `MathFunction`.

It turns out it isn't that hard to implement.  See #29.  I just don't really like it.

**Comment by drgrice1** [comment]
Note the implementation in #29 isn't what I don't like.  It is just supporting `asin` and the ilk in general that I don't like.

**Review by pstaabp — APPROVED** [review]

**Comment by Alex-Jordan** [comment]
I'm testing this as described above (copied the `dist/mathquill.js` file to` /opt/webwork/pg/htdocs/node_modules/mathquill/dist`). I reloaded the a page without using cached js. But it is not changing things. When I type `asin(x)`, MathQuill shows it with a space, but I submit and the feedback reveals PG received `asin(x)` with no space.

I think I copied the right file (the one from this PR branch). I used the one at `https://raw.githubusercontent.com/openwebwork/mathquill/069450f8338d6a4eee544b5b97ed915f317366ae/dist/mathquill.js`.

**Comment by drgrice1** [comment]
I am not sure how that would be happening.  I just tested again as I had described (copied `dist/mathquill.js` to `/opt/webwork/pg/htdocs/mathquill/dist`), and if I enter `asin(x)`, PG shows `a sin(x)` (see the following screenshot).
asin

Testing with the MathQuill dev server, I also see that the output text string is `a sin(x)` as it should be.

**Comment by Alex-Jordan** [comment]
I can't reproduce what I described in my last post. Either I was doing something wrong, or the browser was caching the prior js file. But it works now!

**Review by Alex-Jordan — APPROVED** [review]

**Pull request merged**
