### PR TITLE
Mathquill rewrite

### PR DESCRIPTION
**Pull request by drgrice1**
This includes the changes needed for https://github.com/openwebwork/webwork2/pull/1522 and https://github.com/openwebwork/pg/pull/614.

This is a complete rewrite of MathQuill to build with webpack and typecript.

There are actually other bugs that are fixed that are not mentioned in the webwork/pg pull requests as well.

### CODE REVIEW

**Comment by pstaabp** [comment]
How should we best test this?  Pull the webwork2 and pg branches and test there?

**Comment by drgrice1** [comment]
Yeah, that is the easiest way.  You can also go to the site I gave you yesterday (https://jasper.csmp.missouriwestern.edu/courses/testing/misc/mathquill/mathquill-editor-modular-test.html).  I have the latest version of this active on that site.

**Comment by pstaabp** [comment]
I put in the following in 
image

In your test site, it's parses as:  x^(3+ 1/2 )/4x^-1 +pi 

However submitting it in webwork it parses as [(x^[3+(1/2)])/4]*[x^(-1)]+pi

This doesn't look right.  You had commented on the ability to reduce the number of parens.

**Comment by drgrice1** [comment]
Yeah, it seems that implicit multiplication in the denominator will need parentheses.  The numerator does not.  I will fix that.

**Comment by drgrice1** [comment]
I think I will just add parentheses for the numerator also in this case (it is easier that way as the numerator and denominator use the same code).  This should be fine, and shouldn't affect the issues that this pull request attempts to fix.

Thanks @pstaabp.  Keep testing!

**Comment by drgrice1** [comment]
@pstaapb:  Hmm.  That is more of a problem than I thought.  This does mess with whole issue with units.  For example, if you enter what appears as `\frac{ft}{s^2}`, then adding the fake `implicit multiplication` check that I have it now is submitted to webwork as `(ft)/(s^2)`.  The problem is that MathQuill sees the `f` and `t` in the numerator as separate "variables".  Furthermore, my fake `implicit multiplication` check is really just counting blocks that are not digits and adding one of there are digits, and so the `s^2` is parenthesized.  MathQuill does not really have an implicit multiplication operator.

**Comment by drgrice1** [comment]
I think the only way to do this is to change the way that webwork does parsing when units are needed to allow parentheses after all.

**Comment by pstaabp** [comment]
Could you detect a space between the formula/number and the units and parse the formula and unit separately? I realize that would require that the only space would be between them and not in either formula or unit.

**Comment by pstaabp** [comment]
Another thought.  How about separating the formula and units with a ';'  It seems reasonable to have some separation and a space is pretty arbitrary.

**Comment by drgrice1** [comment]
@pstaapb: Neither of those are really viable options in the context of MathQuill, and the second still requires special parsing on the webwork side.  This is already fixed with my latest commit to the PG pull request.

**Pull request merged**
