### PR TITLE
Update dependencies mostly to resolve security vulnerabilities

### PR DESCRIPTION
**Pull request by drgrice1**
This updates all of the npm dependencies to their latest versions.  The main point of this is to remove security vulnerabilities that have come up with some up the dependencies.

There are some changes that resulted in changes to the distributed javascript and css.  These are minor and mostly due to linting issues and prefixes.  Some of the css classes used a mix of kebab case and camel case which is considered bad.  The css prefixes that were used are all invalid now and the corresponding css rules are standard for all browsers.  If we use any that need prefixes we will need to install autoprefixer.   However, at this point that is not needed.  I tested this and autoprefixer does not add anything for the css in use currently.

Merge sequence order: 1

### CODE REVIEW

**Review by pstaabp — APPROVED** [review]
This looks good.  Now that these dependencies are updated, we probably need to do again 6 months later.

**Comment by drgrice1** [comment]
Yeah, that seems to be the way of things with `node` and `npm`.  These dependencies change rapidly.

**Comment by pstaabp** [comment]
If you want to update packages again, here, I can retest

**Comment by drgrice1** [comment]
@pstaabp: I did another round of updates.  All packages are now at their latest versions except `stylelint` and `stylelint-config-standard`.  Upgrading those further will take some work due to breaking changes with the way they work now.

**Comment by pstaabp** [comment]
> @pstaabp: I did another round of updates. All packages are now at their latest versions except `stylelint` and `stylelint-config-standard`. Upgrading those further will take some work due to breaking changes with the way they work now.

I did notice that those jumped major version numbers, so seems reasonable not to update.  Looked through all the demos and unit tests and looks good.

**Comment by drgrice1** [comment]
One cool feature apparently added to the mocha test suite is that it now supports dark mode.  I have my browser set to dark mode, and noticed that when running the unit tests the background is not white anymore.  I switched my browser to light mode, and it when back to white.

**Comment by pstaabp** [comment]
I run dark mode as well.  I guess I didn't notice the difference. Cool.

**Pull request merged**
