### PR TITLE
Some fixes and tweaks that are needed.

### PR DESCRIPTION
**Pull request by drgrice1**
Fix an issue that is caused by an event being re-dispatched to the wrong element.  The event is instead dispatched to the same element it originally occured on and this causes an infinite recursion.

Fix another issue when the autoSubscriptNumerals option is used.  If `x3` is typed (which shows as x_3), then the down arrow is pressed to go down into the subscript, and then 5 is typed, then the 5 is output twice.  This is due to the need of a return statement in the MathBlock writeMethodMixin write method.

If the rootsAreExponents option is enabled (the default for WeBWork), and a superscript is on the nthroot, then add parentheses around it in the text output.  For example if "root3 4 ^6" is typed, then this will display as the 6th power of the cubed root of 4 (assuming the root autoCommand is enabled -- also a WeBWorK default).  This makes the text output in that case ((4)^(1/3))^6".  The current text output is "(4)^(1/3)^6" which is not mathematically equivalent.  The latex output is correct.

If something to the left of as SupSub (exponent or subscript) is deleted and the new thing to the left is no longer valid for a SupSub to be on then bring its contents out and remove the SupSub.  For example, parentheses are automatically added when a SupSub is placed onto a fraction.  If the parentheses are deleted, then this happens. Also if the supSubsRequireOperand option is enabled (another WeBWorK default) and the base is deleted, then this happens also.  Furthermore, if the new thing on the left is another SubSub, then this is merged with that one.

Also make it so that an nthroot with an index of 2 is submitted as a square root.

Fix the latex command `\ `.  This was a matter of checking for the latex string begin undefined, when it should have been a check if it was empty or undefined.

### CODE REVIEW

**Comment by pstaabp** [comment]
@drgrice1, wondering about a way to test this.  I see that you have unit tests, but it doesn't look like you added some of these cases to it?  That might be the best way to test.

**Comment by drgrice1** [comment]
The easiest way to test is to use the dev server.  Run npm install, and then run npm run serve.  Then open http://localhost:9292/input-test.html in your browser.  This will have an input on the left that shows the text output, and an input on the right that shows the latex output when you type into the math quill box in the middle.

**Comment by pstaabp** [comment]
On the dev server at input-test.html I'm not see the x3 turning into x_3, but it seems like the switch `autoSubscriptNumerals` may not be on for the page. 

I also see that typing 'root' automatically changes to an nth root.  Is this supposed to turn 'root3' automatically into a cube root? 

Related to this, I notice if you type root to get a square root and then skip the number of the root (2,3,...) then the latex is `\sqrt[]{3}` for example. Not sure if the empty [] is a problem.

**Comment by drgrice1** [comment]
The input-test.html uses the same settings that webwork uses.  The autoSubscriptNumerals option is not one of those.  `root` is supposed to turn into an nth root.  If you literally type `root3` you will end up with a root symbol with the index of 3.  Finally, the empty `[]` on the root is not a problem.  That is valid latex.  So in short, everything you observed is working the way it is supposed to.

**Comment by drgrice1** [comment]
To see the `autoSubscriptNumerals` option in action you can either add it in `input-test.html`.

You can observe it in action in `visual-test.html`.  The MathQuill input under `Behavior Options` has this option set.  Although that doesn't show the text and latex output.

**Comment by drgrice1** [comment]
@pstaabp:  I added some options to the input-test.html file.  So now you can change the options and see what they do.  One of the options of course is autoSubscriptNumerals.  Not all of MathQuill's options are represented, but all of them that webwork uses are and a few others.

**Review by pstaabp — COMMENTED** [review]
Revisited this.  Looks good now.

**Pull request merged**
