### PR TITLE
Change Greek letter class and remove deg from operators.

### PR DESCRIPTION
**Pull request by somiaj**
Two updates:

Change Greek letter class from Variable to NonSymbolaSymbol so if they are configured to auto format via `autoCommands`, they don't include a `\` when sending the name to webwork. This is what is already done with `pi`, so changing other Greek letters to match.

Remove deg from the operator list so the units degC, degK, degF, and degrees get sent correctly to webwork.

I put these two changes in a single pull request since rebuilding the library in `dist/` would make them depend on each other anyways.

### CODE REVIEW

**Review by drgrice1 — CHANGES_REQUESTED** [review]
Please separate the commits in this pull request into two separate pull requests.  The two commits deal with completely unrelated things, and they are both going to need changes.  So it would be better to deal with these separately.

I have thought about the first commit that changes lower case Greek letters into `NonSymbolaSymbol`'s, and realized that this approach is not entirely correct.  In so doing the css style that applies to these Greek letters is changed.  Basically, these letters will no longer be italicized as a result.  Many conventions state that when used to represent mathematical variables, Greek letters should be italicized.  On the other Greek letters used to represent mathematical constants (like pi and lambda) should not be italicized.  That is most likely why the MathQuill developers have things the way they have it.  We will need to decide if we want to deviate from that.

As to the issue of having the forward slash, that should simply be removed from all Variable objects.  I have looked at this closely and there is simply no case where something of Variable type should have that forward slash.  This is as simple as deleting lines 466 and 477 of src/commands/mathElements.ts.

I don't have any specific comments for the second commit yet, except that I am certain that is also not the right way to go.  More thought is needed on that.

**Comment by drgrice1** [comment]
@somiaj:  Note that with the way we distribute the dist every pull request needs to update the dist build when another pull request is merged in any case.  So when these are separated, whenever the other is merged that will need to be done.

**Comment by somiaj** [comment]
That was the reason I put them in the same pull request to simplify having to rebuild the dist directory depending on which order they were merged.

Thanks for pointing out how to remove just the backslash from the submitted variables. I didn't see how to do that, and when I saw what was done for pi, I just followed that since it was the only Greek letter I had to work from.

I have created a new pull request for removing the backslash. I am closing this one.

As for removing deg from the operator list, there was discussion about removing almost all of the operators (since they aren't really used by pg) and add some sort of option to allow problems to add operators to the list for specific problems as needed. So I won't create a pull request for that, unless there is reason to just remove most of them now and worry about adding the feature to add operators later.

**Comment by drgrice1** [comment]
For now just leave the operators.  We should discuss this at our next meeting.

**Pull request closed without merging**
